### ISSUE TITLE
Deposit issue

### ISSUE THREAD

**Issue by Ricardonacif** [Bitsino/BitsinoDice#1]
Hey guys,

I have made a deposit to https://blockchain.info/address/35WMeBKjokr9XwaZeTvo8LrnHwVT4Z2Nk3 but it didn't appeared on my balance. Is it working?

Btw, nice project :D

**Comment by ianpurton** [comment]
Looking at this now.

**Comment by ianpurton** [comment]
Should be fine now, can you check your balance  ?

**Comment by Ricardonacif** [comment]
It's fine now. Do you know why did it take so long?

**Comment by ianpurton** [comment]
There's seems to be a problem with taking deposits from the blockchain. We basically sweep the blockchain every ten minutes, I think the issue is that we may be skipping a block just as coins arrive.

So I'll need to get a fix in for that.

**Comment by Ricardonacif** [comment]
Where at the code are you checking that? I didn't find it.

**Comment by ianpurton** [comment]
https://github.com/Bitsino/BitsinoDice/blob/master/app/models/user.rb#L34

This uses the onchain API available here. https://github.com/onchain/onchain-gem

**Comment by Ricardonacif** [comment]
Got it, but is there a worker that does that?

**Comment by ianpurton** [comment]
Yes. It's called from a rake task. https://github.com/Bitsino/BitsinoDice/blob/master/lib/tasks/scheduler.rake#L6

**Comment by Ricardonacif** [comment]
But are you hosting it on Heroku? How often does those tasks run? Is it automatic?

**Comment by ianpurton** [comment]
Yes, Heroku supports scheduled tasks. This task runs every ten minutes which roughly lines up with new block gerneration times. https://devcenter.heroku.com/articles/scheduler

**Comment by Ricardonacif** [comment]
Nice! Thanks @ianpurton, nice job here :)

**Comment by ianpurton** [comment]
You're welcome.

**Comment by Ricardonacif** [comment]
Btw, does the cashout rake task run every 10 minutes? I'm still awaiting for mine, and it's been 23 minutes.

**Comment by ianpurton** [comment]
That runs every 24 hours at the moment, this is during the early days I want to be able to check all payments in and out.

**Comment by Ricardonacif** [comment]
Got it :D

**Comment by Ricardonacif** [comment]
Hey Ian,

I'm running it locally, I have created a onchain account, have created a user, sent some bitcoins, played with it, and requested for a checkout. These are my questions:

1- The cashout is not implemented yet, right? How can I do it manually?
2- How can I get access to the funds on the main account?
3- What's the stage of the development of this?

Thanks,

**Comment by ianpurton** [comment]
@Ricardonacif 
1. Cashout is being implemented today. You should start to see some checkins in a few hours.
2. Do you mean the onchain account ? Click send bitcoins to transfer the funds anywhere you like.
3. After cashout is implemented and tested we will start to promote the site more. This should shake out some more bugs. So the product is in early development.

**Comment by Ricardonacif** [comment]
Really nice Ian. Do you want me to contribute to the project by adding a bo painel using active_admin?

**Comment by ianpurton** [comment]
@Ricardonacif Sounds great. Yes, why not.

**Comment by Ricardonacif** [comment]
I will start to work on that this week so. I have a few more questions to you (sorry to bother again):

1- On my copy of the project hosted on heroku, the deposits I made are still waiting for sign off. How can I do that?
2- Even after sending a small amount of bitcoins to there, it isn't appearing on my Onchain account. How does that works? 
3- Where should I deposit the "House funds"?

Thanks,

**Comment by ianpurton** [comment]
@Ricardonacif 
1. Do you mean your withdrawals are awaiting signoff ?
2. You need to run the sweep_tx task. This will create a transaction and send it to onchain. From your onchain account you can then sign the transaction sending the bitcoins into your fund.
3. You can keep your "House funds" in the onchain fund or anywhere else. You can then top up the fund as needed to be able to make your payouts. Hopefully your onchain fund grows quicker than your need to make payouts.

Thanks.

**Comment by Ricardonacif** [comment]
@ianpurton 
1- Yeah. How can I sign them off?
2- I'll try that.
3- Thanks

**Comment by ianpurton** [comment]
@Ricardonacif 

When you create the payment, go to the transactions menu. You should see your TX. Click on it and enter your passphrase.

Hope this helps.

**Comment by Ricardonacif** [comment]
I'm waiting for a withdraw to be signed off from http://bitcoinary.com/, can you please take a look?

Thanks,

**Comment by ianpurton** [comment]
@Ricardonacif Taking a look now to see why it hasn't gone through.

**Comment by Ricardonacif** [comment]
Great, let me know if you have any updates!

**Comment by ianpurton** [comment]
@Ricardonacif What's your user id ?

**Comment by Ricardonacif** [comment]
44

**Comment by ianpurton** [comment]
OK. It's paid now. Sorry about that.

**Comment by Ricardonacif** [comment]
Hey Ian, 

Looks like you sent me 0.127 instead of 0.0127 lol. I appreciate your generosity, but I'm pretty sure it was accidental :+1: Where can I send it back?
